# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: Selfhosted

variables:
  buildConfiguration: 'Release'
  proyectoMVC: 'ManejoDeTareas/ManejoDeTareas.csproj'

steps:
- task: UseDotNet@2
  displayName: 'Instalar .NET 8 SDK'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  displayName: 'Restaurar dependencias'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Instalar EF Tools'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global dotnet-ef --ignore-failed-sources'

- script: dotnet ef --version
  displayName: 'Verificar EF Tools'

- script: |
    cd "$(Build.SourcesDirectory)/ManejoDeTareas"
    dotnet ef database update --connection "$(DefaultConnection)"
  displayName: 'Aplicar migraciones EF'

- task: DotNetCoreCLI@2
  displayName: 'Construyendo los artefactos...'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: $(proyectoMVC)
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/webapp --runtime win-x86 --self-contained'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  displayName: 'Publicando los artefactos'