# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: Selfhosted

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  proyectoMVC: 'ManejoDeTareas/ManejoDeTareas.csproj'

steps:
- task: UseDotNet@2
  displayName: 'Instalar .NET 8 SDK'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  displayName: 'Restaurar dependencias'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Instalar EF Tools'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global dotnet-ef'

- script: dotnet ef database update --project "$(Build.SourcesDirectory)/ManejoDeTareas/ManejoDeTareas.csproj" --startup-project "$(Build.SourcesDirectory)/ManejoDeTareas/ManejoDeTareas.csproj" --configuration $(buildConfiguration)
  displayName: 'Aplicar migraciones EF'
  
- task: DotNetCoreCLI@2
  displayName: 'Construyendo los artefactos...'
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: 'database update --project $(proyectoMVC) --startup-project $(proyectoMVC) --configuration $(buildConfiguration)'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  displayName: 'Publicando los artefactos'
